version: 0.0
os: linux
files:
  - source: /app.jar
    destination: /home/ubuntu/app/
    # owner: ubuntu # 필요하다면 파일 소유자도 지정
    # group: ubuntu # 필요하다면 파일 그룹도 지정

  # scripts 폴더 안의 각 스크립트에 대해 실행 권한(mode: 755)을 명시적으로 부여합니다.
  #  deploy.zip 안에는 'appspec.yml'과 'scripts/' 폴더가 같은 레벨에 있어야 함
  - source: /scripts/before_install.sh
    destination: /home/ubuntu/app/scripts/before_install.sh # EC2 인스턴스의 실제 경로
    mode: 755
    owner: ubuntu # 스크립트를 실행할 사용자 (hooks의 runas와 일치시키는 것이 좋음)
    group: ubuntu

  - source: /scripts/after_install.sh
    destination: /home/ubuntu/app/scripts/after_install.sh # EC2 인스턴스의 실제 경로
    mode: 755
    owner: ubuntu
    group: ubuntu

  - source: /scripts/application_start.sh
    destination: /home/ubuntu/app/scripts/application_start.sh # EC2 인스턴스의 실제 경로
    mode: 755
    owner: ubuntu
    group: ubuntu

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh # deploy.zip 내의 상대 경로
      timeout: 300
      runas: ubuntu

  AfterInstall:
    - location: scripts/after_install.sh # deploy.zip 내의 상대 경로
      timeout: 300
      runas: ubuntu

  ApplicationStart:
    - location: scripts/application_start.sh # deploy.zip 내의 상대 경로
      timeout: 300
      runas: ubuntu