name: Deploy Spring Boot to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Prepare deployment package
        run: |
          mkdir deploy
          cp build/libs/*.jar deploy/app.jar
          cp appspec.yml deploy/
          cp -r scripts deploy/
          cd deploy
          zip -r deploy.zip *

      - name: Upload to S3
        env:
          AWS_REGION: ap-northeast-2
        run: |
          aws s3 cp deploy/deploy.zip s3://${{ secrets.S3_BUCKET_NAME }}/deploy/deploy.zip

      - name: Deploy with CodeDeploy
        uses: aws-actions/aws-codedeploy@v1
        with:
            application-name: test_cicd
            deployment-group: test-cicd-deploygroup
            wait-for-deployment: true
            s3-location: |
              bucket=${{ secrets.S3_BUCKET_NAME }}
              key=deploy/deploy.zip
              bundleType=zip
