name: Deploy to EC2 with CodeDeploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: ap-northeast-2

    - name: Zip application
      run: |
        zip -r deploy.zip app.py appspec.yml scripts/

    - name: Upload to S3
      run: |
        aws s3 cp deploy.zip s3://ttasup-dev-bucket/deploy/deploy.zip

    - name: Deploy with CodeDeploy
      run: |
        aws deploy create-deployment \
          --application-name test_cicd \
          --deployment-group-name test_cicd_deploygroup \
          --s3-location bucket=ttasup-dev-bucket,key=deploy/deploy.zip,bundleType=zip \
          --file-exists-behavior OVERWRITE
